#!/bin/bash
echo Hey There
pat="$(cat isiodor_mordor)"
cd /Users/pyadhe/movies

{ 
    mkdir "PD_SubsRETR"
} || { 
 echo ""
}

cd /Users/pyadhe/movies/PD_SubsRETR/

nam=""
for f in "$@"
do
nam="$nam $f"
done

python /Users/pyadhe/Documents/iTest/testBash/macBash/sbt.py $nam
