#!/bin/bash
echo Hey There
cd /Users/pyadhe/movies
mkdir "PD_SubsRetr"
cd /Users/pyadhe/movies/PD_SubsRetr/

nam=""
for f in "$@"
do
nam="$nam $f"
done

python /Users/pyadhe/Documents/iTest/testBash/macBash/sbt.py $nam
